* Sound THUMB! wind 管乐之风谱面编辑器用户手册
** 如何构建
本软件使用 xmake 构建, 并使用了 raylib 图形库, 因而具有良好的跨平台能力. 以下给出 macOS 与 Windows 下的构建方法, 已在 macOS Catalina (10.15.2) 与 Windows 10 (1903) 上进行了实验. 使用 xmake v2.2.9 及 raylib 2.5

1. 安装 xmake 构建工具
2. 参考 raylib wiki 构建最新版本的 raylib
3. 进入到想要构建安装编辑器的目录, 运行以下 shell 代码
#+BEGIN_SRC sh
git clone git@github.com:Yunoinsky/Sound_THUMB-wind.git
#+END_SRC
或使用 https 协议
#+BEGIN_SRC sh
git clone https://github.com/Yunoinsky/Sound_THUMB-wind.git
#+END_SRC
您可以随时使用以下命令来跟进项目
#+BEGIN_SRC sh
git pull
#+END_SRC

4. 接下来, 运行以下命令, 建立 lib 文件夹
#+BEGIN_SRC sh
cd Sound_THUMB-wind
mkdir lib
#+END_SRC
之后将第二步构建好的 raylib.a 库文件拷贝到 lib 文件夹下

5. 在目录下运行以下命令, 完成构建
#+BEGIN_SRC sh
xmake build Editor
#+END_SRC
即可以看到 build 目录下的 Editor.exe (macOS 下为 Editor), 双击或运行以下命令即可打开:
#+BEGIN_SRC sh
xmake r Editor
#+END_SRC

PS: window 下如果需要添加图标, 请在项目目录下创建 res 文件夹, 并将需要添加的图标(如 thumb.ico)拷贝到 res 文件夹下.
在同一目录下创建平文本的资源文件 thumb.rc, 内容为
#+BEGIN_SRC
id ICON thumb.ico
#+END_SRC
thumb.ico 为图标文件名
在该目录下运行
#+BEGIN_SRC sh
windres thumb.rc -o thumb.o
#+END_SRC
之后再进行第五步的构建即可
如果需要进行linux的构建, 请对需要添加的库进行一些修改, 参考 [[https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux][raylib wiki]] 

PS2: 目前尚未添加对于 windows 窗口的支持, 因而在 win 下运行时会有默认的命令行弹出, 如果想要消除命令行, 可以在 Editor.exe 所在的目录下创建启动用的 vbs 文件, 内容如下:
#+BEGIN_SRC sh
CreateObject("Wscript.Shell").run "Editor.exe", vbhide
#+END_SRC
之后再通过双击 vbs 文件打开即可

** 使用手册
*** 音频文件准备
1. 首先, 确定你所使用的音乐为 mp3, ogg, wav 或 flac 格式, 如果不是这些常用格式, 请使用 ffmpeg 等工具进行转码
2. 将文件名改为简单的数字+英文名, 建议参考资源管理规范进行格式化命名
3. 确保音频文件存放在英文路径下 (之后会考虑支持中文目录)
4. 如果需要编辑对应音频文件的谱面, 请将与音频文件同名且以 .wind 后缀结尾的谱面文件存放在与程序文件一致的目录下
*** 打开文件
1. 双击打开编辑器后, 会直接进入到打开文件窗口
2. 将之前准备好的音频文件拖拽到打开文件窗口下, 待加载完毕后点击 *confirm* 进行确认. 如果拖拽了错误的文件, 请点击 *cancel* 取消后再拖拽入正确的文件.
*** 音频播放
1. *空格键* 或单击播放按钮可以进行音频播放, 再次空格或单击暂停按钮可以停止
2. 单击停止按钮可以结束音频播放并返回开头
3. 使用 *A*, *D* 键或单击进退按钮可以向前后跳转; *Q*, *E* 键为精细跳转; 使用鼠标滚轮也可以实现同样的功能
4. 单击播放控件左侧的按钮可以关闭目前播放的文件并重新进入打开文件窗口, 请注意, 这一步不会自动保存, 请提前完成保存
*** 谱面编辑
**** 选择编辑模式
按 *<Shift> + 1* 可以进入选择编辑模式
在非播放状态下可以选中音符并进行编辑, 选中后, 右侧模式面板即会同步到所选音符的信息
在右侧模式面板对所选音符信息进行修改后, 单击 *Confirm* 或 *<回车键>* 即可完成对该音符的修改, 单击 *Cancel* 可以取消修改, 单击 *Delete* 或 *<退格键>* 即可删除音符
**** 拖拽模式
按 *<Shift> + 2* 可以进入拖拽模式
在拖拽模式下可以点选任何音符, 即可进行音符的拖拽. 再次单击即可将该音符插入到新的位置. 
拖拽模式实际上是将音符拿起并进入响应的添加模式, 因而两次单击之间不需要保持鼠标按键.
**** 添加模式
按 *<Shift> + 3~9* 可进入七种音符的添加模式
在添加模式中, 使用 *T* 可以保持音符紧贴播放线
单击即可完成添加.
在添加完毕后, 可以进入到选择模式中对细节进行进一步编辑
**** 保存
使用 *<Shift> + 0* 可以完成谱面的保存, 会以音频文件名及 .wind 后缀保存在程序文件所在目录下
保存后会进入插入模式
*** 谱面规则
1. 同轨的两个音符间距请不要小于 120 ms
2. 有七种音符:
- 单击: Click 键, 为蓝色
- 滑键: Slip 键, 为粉色, 并具有粉色的滑动方向, 可以设置左, 中(上), 右三种滑动方向
- 保持键: Hold 键, 为棕色, 并具有棕色的保持路径, 保持键需要以结束键结束, 其间不允许其他音符插入
- 锁链开始键: Drag 键, 为紫色, 并具有粉色的拖拽路径, 可以设置左, 中, 右三种拖拽方方向, 锁链开始键象征着一条拖拽路径的起始, 其后必须连接到对应方向上的锁链经过键或结束键. 在锁链开始后, 起始轨道上可以添加其他键, 但目标轨道则不能被占用, 否则锁链无效.
- 锁链经过键: Pass 键, 为浅紫色, 性质与锁链开始键相同, 象征着拖拽路径的经过
- 结束键: End 键, 为深棕色, 对应锁链或保持键的结束
- 功能键: Fun 键, 为黄色, 目前具有 禁用轨道, 启用轨道, 轨道华彩和华彩结束四种功能. 一开始的所有轨道默认为禁用, 需要手动启用. 每个禁用都需要与启用对应, 并在其间具有灰色的路径. 每个轨道华彩都需要与华彩结束相对应, 并具有金色的路径
